### ISSUE TITLE
Some of the points covered by the path are biased

### ISSUE THREAD

**Issue by ZengJunTao111** [ipa320/ipa_coverage_planning#24]
Dear author, I have modified part of the Boustrophedon Coverage Path Planning parameter Settings to achieve the results as shown below, there are some minor problems, may I ask what causes some points to deviate? How to achieve a result like the second figure?
![6bd381f112a03ae3223a7ec80050475](https://github.com/ipa320/ipa_coverage_planning/assets/132878810/2a69de07-2abb-4d62-9bcc-3e319a96cbab)
<img width="469" alt="8a78880c2da1edd8219ecfb2fe9ce90" src="https://github.com/ipa320/ipa_coverage_planning/assets/132878810/39cf0cc3-9c7b-409c-b046-8ff7c9de0248">

**Comment by ipa-foj** [comment]
As mentioned in #23 we use the segmentation ground-truth data in the paper instead of the segmentation module provided in the repo. In your case this boils down to setting the parameters of the modules s.t. your desired outcome is achieved or using the code in another way. 

As there seems to be no issue with the code or with running it, this issue is closed.

**Comment by ZengJunTao111** [comment]
Ok, thank you very much
